### ISSUE TITLE
Multiple fields with same name are allowed to define in the same class?

### ISSUE THREAD

**Issue by danielsun1106** [danielsun1106/groovy-parser#10]
@blackdrag @paulk-asert 

The following code is extracted from gradle project(subprojects/core/src/test/groovy/org/gradle/execution/TaskNameResolverTest.groovy).

As we can see, there are 2 fields named `resolver`, as a result, one of the two does not appear at ClassNode.fields, i.e. it is replaced by another. 

IMO, the code does not conform to GLS, should we support it or add some syntax check to forbidden?

``` groovy
// code snippet from gradle
class TaskNameResolverTest extends Specification {
    def tasks = Mock(TaskContainerInternal)
    def project = Mock(ProjectInternal)
    def resolver = new TaskNameResolver()

    def setup() {
        _ * project.getTasks() >> tasks
    }

    private final TaskNameResolver resolver = new TaskNameResolver()
```

``` groovy
// FAILED
class A {
    def x = 1
    def y = 2
    def z = 3
    private final Z z = 4
}

// PASS
class A {
    def x = 1
    def y = 2
    def z = 3
    private final Z z2 = 4
}
```

**Comment by blackdrag** [comment]
should not be allowed, yes.

**Comment by danielsun1106** [comment]
I see :)

**Comment by paulk-asert** [comment]
I created this issue to track this bug in the apache/groovy repo:
https://issues.apache.org/jira/browse/GROOVY-7968

**Comment by paulk-asert** [comment]
@blackdrag, seems like we specifically allowed the field and property as
per https://issues.apache.org/jira/browse/GROOVY-2864

I don't think I really like this but what do you think?

**Comment by blackdrag** [comment]
Actually I did not realize the problem here was about a field and a property of the same name. Shame on me. I really think such checks have no place in the parser. The parser needs to be doing checks only in so far as that we can create an initial AST from it, nothing more. Anything else should be left to the compiler itself. 

Now as for the issue itself.  "private String x; def x" and "def x; private String x" must behave the same. There is also the case of "class A { public x}; class B extends A{ def x}", which I see related. Here it is in theory legal to give B its own field x, but I think it should reuse the field instead. If we disallow this in the same class, then I don't see why we should be allowing it with the inheritance case. But the inheritance case looks to me as a case we clearly want to allow. Thus my conclusion would be to allow it.

**Comment by paulk-asert** [comment]
Not sure what you mean by "... would be to allow it"? Do you mean allow it in the same class because we might want to allow it through inheritance?

We currently don't have the same behavior in those two cases anyway:
```
class Base {
  public int x = 2
}
class Foo extends Base {
  int x = 1
}
class Bar {
  public int x = 2
  int x = 1
}
println new Foo().x // => 1
println new Bar().x // => 2
```
And that bad thing about the `Bar` class is that you don't know which of the initializers is in play.

**Comment by blackdrag** [comment]
am am for more fun, make Bar extend Base ;) But yes

**Comment by paulk-asert** [comment]
For me you'd fall back to Java as much as possible, so it would be an error to have a property and field of the same name in the same class. If there is a field in a super class, a property in the child class with the same name would mask the super field which could only be retrieved using the "super." prefix.

**Comment by blackdrag** [comment]
You cannot fall back to Java for a feature Java does not have. But anyway...if we do not reuse in the B extends A example, then I currently tend to say that this is wrong. But maybe it boils down to the question of if the backing field of the property is an implementation detail or not. if it is, then we should not have direct access to it and the name can be anything. We don't live that. Thus for me the field is part of the property under a specific name in Groovy. We do allow to specify getter and setter for the property, why not the field? And I think we should not only include the current class for this, but also the super class. And when we produce the getter and setter for a property we actually do take existing method of the current class and the super classes into account, why not for the field?

**Comment by paulk-asert** [comment]
The model I've always had in my head for a Groovy property is that it is short for a getter, setter (unless final) and backing field. Inheritance doesn't really come in to play, the property gives you a new field and accessor methods. This seems to be what we support:
```
class Base {
  private int foo = 1
  int getFoo() {
    3
  }
}

class Child extends Base {
  int foo = 5
}

assert new Child().foo == 5
```
We always give a new one and complain if the new one we give you doesn't match, e.g.:
```
class Child extends Base {
  Date foo = 5
}
// Compilation error: The return type of java.util.Date getFoo() in Child is incompatible with int in Base
```

**Comment by paulk-asert** [comment]
Similarly, for fields:
```
class Base {
  public String bar = 'base'
}

class Child extends Base {
  public String bar = 'child'
}

assert new Child().bar == 'child'
```

**Comment by paulk-asert** [comment]
Looking back through the Jiras, I think the only reason that we support the current behavior is because the grails build was failing because we were adding both a metaclass backing field and a property but that was probably a bug in grails.

**Comment by danielsun1106** [comment]
http://groovy.329449.n5.nabble.com/About-declaring-the-field-and-property-with-same-name-tp5742010p5742073.html
