### ISSUE TITLE
The first character of class name is required uppercase in variable declaration but not required in the class declaration

### ISSUE THREAD

**Issue by danielsun1106** [danielsun1106/groovy-parser#2]
**In the following variable declaration, the first character of class name should be uppercase:**
```groovy
SomeType st; // defining a variable named st whose type is SomeType
someType st; // same as: someType(st); it is a parenthesis-less method call
```

**but we can declare a class whose name is lowercase:**
```groovy
// benchmark/bench/ary.groovy
public class ary {
}
```
**The different standard of class name can introduce some potential issue.** 

@blackdrag
**Jochen, should we unify the standard of naming in the new parser?**

**Comment by blackdrag** [comment]
The reason this is in the old parser is because of us not easily be able to tell if "foo b" is a method call or a declaration. For example, let us assume we recognize this as declaration... then we have to wait till after the class resolving step to make this a method call. And if "foo" is supposed to be a class? Or see it the other way around... assume you want it to be a method call. You test your application and everything is fine. You distribute in source and suddenly your application no longer works, because there is suddenly a foo class on the classpath. Well... but maybe we can go with variant 1 and see it as a declaration by default with later transformation... could break some code here and there though....  if we had something that says that this may be a method call or a declaration... then programs could at least react to it.

**Comment by danielsun1106** [comment]
I see. Thank you, Jochen :)

**Comment by danielsun1106** [comment]
Fixed by https://github.com/danielsun1106/groovy-parser/commit/7e696679c2cd077b5d939f8de8a5b8112b232e80
